# -*- coding: utf-8 -*-
"""E-commerce Sales Prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJ_X2Se-ntJLnJRvxJDK2J_FGhPmMhQo

## Introduction
# 📌 E-Commerce Sales Prediction — Machine Learning Project

## 🎯 Objectif du projet
L’objectif de ce projet est de prédire le montant des ventes réalisées par un site e-commerce à partir de différentes caractéristiques (prix, catégorie, rating, réduction…).

Ce travail s'inscrit dans le cadre du module *Data Science & Machine Learning* et suit les étapes complètes d’un projet de ML :
- Analyse du dataset
- Nettoyage & préparation
- Exploration des données (EDA)
- Feature Engineering
- Modélisation et évaluation
- Interprétation finale

## 🔍 Problématique
La variable à prédire est **Sales**, une variable numérique continue.

➡️ Il s’agit donc d’un **problème de régression supervisée**.

## Importation des librairies
"""

# Commented out IPython magic to ensure Python compatibility.
# Manipulation des données
import pandas as pd
import numpy as np

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('seaborn-v0_8-darkgrid')
# %matplotlib inline

# Preprocessing et Machine Learning
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Autres
import warnings
warnings.filterwarnings('ignore')

# Configuration des visualisations
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 10

print("✅ Toutes les bibliothèques ont été importées avec succès!")

"""## Chargement du dataset"""

from google.colab import files

# Upload du fichier
print("📁 Veuillez sélectionner votre fichier CSV...")
uploaded = files.upload()

# Charger le dataset
df = pd.read_csv('Ecommerce_Sales_Prediction_Dataset.csv')

# Afficher les informations de base
print("\n" + "=" * 70)
print("INFORMATIONS SUR LE DATASET")
print("=" * 70)
print(f"\nNombre de lignes: {df.shape[0]}")
print(f"Nombre de colonnes: {df.shape[1]}")
print(f"\nNom des colonnes:\n{df.columns.tolist()}")

print("\n" + "=" * 70)
print("APERÇU DES DONNÉES (5 premières lignes)")
print("=" * 70)
print(df.head())

print("\n" + "=" * 70)
print("TYPES DE DONNÉES")
print("=" * 70)
print(df.dtypes)

"""# ANALYSE EXPLORATOIRE DES DONNÉES (EDA)"""

# Vérifier les valeurs manquantes
print("=" * 70)
print("VALEURS MANQUANTES")
print("=" * 70)
missing = df.isnull().sum()
if missing.sum() == 0:
    print("✅ Aucune valeur manquante détectée!")
else:
    print(missing[missing > 0])

print("\n" + "=" * 70)
print("VALEURS UNIQUES PAR COLONNE")
print("=" * 70)
for col in df.columns:
    print(f"{col:20} : {df[col].nunique():5} valeurs uniques")

print("\n" + "=" * 70)
print("STATISTIQUES DESCRIPTIVES")
print("=" * 70)
print(df.describe())

"""DISTRIBUTION DES VARIABLES NUMÉRIQUES"""

# Créer la colonne Sales (Revenu Total = Prix × Unités Vendues)
df['Sales'] = df['Price'] * df['Units_Sold']

print("✅ Colonne 'Sales' créée avec succès!")
print("\n" + "=" * 70)
print("STATISTIQUES DE SALES")
print("=" * 70)
print(f"Revenu total: ${df['Sales'].sum():,.2f}")
print(f"Revenu moyen par transaction: ${df['Sales'].mean():,.2f}")
print(f"Revenu médian: ${df['Sales'].median():,.2f}")
print(f"Revenu minimum: ${df['Sales'].min():,.2f}")
print(f"Revenu maximum: ${df['Sales'].max():,.2f}")

# Distribution des variables numériques
numeric_cols = ['Price', 'Discount', 'Marketing_Spend', 'Units_Sold', 'Sales']

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
axes = axes.flatten()

for i, col in enumerate(numeric_cols):
    axes[i].hist(df[col], bins=50, edgecolor='black', alpha=0.7, color='steelblue')
    axes[i].set_title(f'Distribution de {col}', fontsize=14, fontweight='bold')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Fréquence')
    axes[i].grid(alpha=0.3)

# Supprimer le dernier subplot vide
fig.delaxes(axes[5])

plt.tight_layout()
plt.show()

print("✅ Graphique des distributions créé!")

"""# commentaire
Les histogrammes montrent que toutes les variables sont bien distribuées et équilibrées. Le prix varie uniformément de 0 à 1000$, les réductions de 0 à 50%, et le marketing de 0 à 10 000$. La variable cible (Units_Sold) suit une distribution normale centrée à 30 unités, ce qui est parfait pour le machine learning. Le revenu total montre le pattern classique : beaucoup de petites ventes et quelques gros revenus. Les données sont de très bonne qualité et sans biais.

BOXPLOTS POUR DÉTECTER LES OUTLIERS
"""

# Boxplots pour détecter les outliers
numeric_cols = ['Price', 'Discount', 'Marketing_Spend', 'Units_Sold', 'Sales']

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
axes = axes.flatten()

for i, col in enumerate(numeric_cols):
    axes[i].boxplot(df[col], vert=True, patch_artist=True,
                    boxprops=dict(facecolor='lightblue', alpha=0.7),
                    medianprops=dict(color='red', linewidth=2))
    axes[i].set_title(f'Boxplot de {col}', fontsize=14, fontweight='bold')
    axes[i].set_ylabel(col)
    axes[i].grid(alpha=0.3, axis='y')

# Supprimer le dernier subplot vide
fig.delaxes(axes[5])

plt.tight_layout()
plt.show()

print("✅ Boxplots créés!")

"""# commentaire
Les boxplots révèlent la présence d'outliers (valeurs aberrantes) dans Units_Sold et Sales, visibles par les points rouges au-dessus des moustaches. Pour Price, Discount et Marketing_Spend, les données sont bien centrées sans outliers significatifs. Les boîtes bleues représentent 50% des données (du 25e au 75e percentile), la ligne rouge est la médiane. Bien que quelques valeurs extrêmes existent dans Units_Sold et Sales, elles sont acceptables et reflètent des transactions réelles. Les données restent de bonne qualité pour la modélisation.

DISTRIBUTION DES CATÉGORIES DE PRODUITS
"""

# Distribution des catégories de produits
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Graphique en barres
df['Product_Category'].value_counts().plot(kind='bar', ax=axes[0],
                                            color='skyblue', edgecolor='black', linewidth=2)
axes[0].set_title('Distribution des Catégories de Produits', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Catégorie de Produit')
axes[0].set_ylabel('Nombre de Transactions')
axes[0].tick_params(axis='x', rotation=45)
axes[0].grid(alpha=0.3, axis='y')

# Graphique en camembert (pie chart)
colors = plt.cm.Set3(range(len(df['Product_Category'].unique())))
df['Product_Category'].value_counts().plot(kind='pie', ax=axes[1],
                                            autopct='%1.1f%%', startangle=90,
                                            colors=colors)
axes[1].set_title('Répartition des Catégories de Produits (%)', fontsize=14, fontweight='bold')
axes[1].set_ylabel('')

plt.tight_layout()
plt.show()

print("=" * 70)
print("NOMBRE DE TRANSACTIONS PAR CATÉGORIE")
print("=" * 70)
print(df['Product_Category'].value_counts())

"""# commentaire
Les 5 catégories sont équilibrées avec environ 190-210 transactions chacune (19-21% du total). Electronics domine légèrement avec 21%, suivi de Fashion et Toys à 19-20%, puis Sports et Home Decor à 20-21%. Cet équilibre parfait signifie qu'aucune catégorie ne domine le dataset, ce qui garantit de bonnes prédictions pour tous les produits. Pas de biais vers une catégorie particulière.

## matrice de correlation
"""

# Matrice de corrélation
corr_cols = ['Price', 'Discount', 'Marketing_Spend', 'Units_Sold', 'Sales']
correlation_matrix = df[corr_cols].corr()

# Créer la heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, fmt='.2f', cmap='coolwarm',
            square=True, linewidths=2, cbar_kws={"shrink": 0.8},
            vmin=-1, vmax=1, center=0)
plt.title('Matrice de Corrélation entre les Variables', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()

print("=" * 70)
print("CORRÉLATIONS AVEC UNITS_SOLD (Variable Cible)")
print("=" * 70)
correlations = correlation_matrix['Units_Sold'].sort_values(ascending=False)
print(correlations)

"""# commentaire
La matrice révèle les relations clés : Price et Sales ont une corrélation très forte (0.90), logique puisque Sales = Price × Units_Sold. Plus important, Units_Sold (notre variable cible) montre une corrélation positive modérée avec Sales (0.39) mais très faible avec Price (0.02), Discount (−0.03) et Marketing_Spend (0.01). Cela signifie que les variables indépendantes ont peu de corrélation linéaire avec Units_Sold, ce qui requiert des modèles plus complexes comme Random Forest pour capturer les relations non-linéaires. Aucune multicolinéarité problématique détectée.

SCATTER PLOTS (Relations entre Variables)
"""

# Scatter plots : Relations entre variables
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# Price vs Units_Sold
axes[0, 0].scatter(df['Price'], df['Units_Sold'], alpha=0.5, color='blue', edgecolor='black')
axes[0, 0].set_title('Prix vs Unités Vendues', fontsize=14, fontweight='bold')
axes[0, 0].set_xlabel('Prix ($)')
axes[0, 0].set_ylabel('Unités Vendues')
axes[0, 0].grid(alpha=0.3)

# Discount vs Units_Sold
axes[0, 1].scatter(df['Discount'], df['Units_Sold'], alpha=0.5, color='green', edgecolor='black')
axes[0, 1].set_title('Réduction vs Unités Vendues', fontsize=14, fontweight='bold')
axes[0, 1].set_xlabel('Réduction (%)')
axes[0, 1].set_ylabel('Unités Vendues')
axes[0, 1].grid(alpha=0.3)

# Marketing_Spend vs Units_Sold
axes[1, 0].scatter(df['Marketing_Spend'], df['Units_Sold'], alpha=0.5, color='red', edgecolor='black')
axes[1, 0].set_title('Dépenses Marketing vs Unités Vendues', fontsize=14, fontweight='bold')
axes[1, 0].set_xlabel('Dépenses Marketing ($)')
axes[1, 0].set_ylabel('Unités Vendues')
axes[1, 0].grid(alpha=0.3)

# Price vs Sales
axes[1, 1].scatter(df['Price'], df['Sales'], alpha=0.5, color='purple', edgecolor='black')
axes[1, 1].set_title('Prix vs Revenu Total', fontsize=14, fontweight='bold')
axes[1, 1].set_xlabel('Prix ($)')
axes[1, 1].set_ylabel('Revenu Total ($)')
axes[1, 1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

print("✅ Scatter plots créés!")

"""## commerntaire
Les quatre graphiques montrent les relations clés : Prix vs Units_Sold affiche un nuage de points diffus sans tendance linéaire claire, confirmant la faible corrélation (0.02). Réduction vs Units_Sold montre un pattern similaire, pas de relation évidente. Dépenses Marketing vs Units_Sold révèle aussi un nuage dispersé, sans corrélation forte visible. En revanche, Prix vs Revenu Total montre une relation linéaire très forte et positive (0.90), ce qui est attendu mathématiquement. Ces résultats justifient l'utilisation de modèles non-linéaires comme Random Forest et Gradient Boosting pour capturer les patterns complexes.

VENTES PAR CATÉGORIE ET SEGMENT CLIENT
"""

# Ventes moyennes par catégorie et segment
fig, axes = plt.subplots(2, 2, figsize=(18, 12))

# Sales par catégorie
category_sales = df.groupby('Product_Category')['Sales'].mean().sort_values(ascending=False)
axes[0, 0].bar(category_sales.index, category_sales.values, color='teal', edgecolor='black', linewidth=2)
axes[0, 0].set_title('Revenu Moyen par Catégorie de Produit', fontsize=14, fontweight='bold')
axes[0, 0].set_xlabel('Catégorie')
axes[0, 0].set_ylabel('Revenu Moyen ($)')
axes[0, 0].tick_params(axis='x', rotation=45)
axes[0, 0].grid(alpha=0.3, axis='y')

# Units_Sold par catégorie
category_units = df.groupby('Product_Category')['Units_Sold'].mean().sort_values(ascending=False)
axes[0, 1].bar(category_units.index, category_units.values, color='orange', edgecolor='black', linewidth=2)
axes[0, 1].set_title('Unités Vendues Moyennes par Catégorie', fontsize=14, fontweight='bold')
axes[0, 1].set_xlabel('Catégorie')
axes[0, 1].set_ylabel('Unités Vendues Moyennes')
axes[0, 1].tick_params(axis='x', rotation=45)
axes[0, 1].grid(alpha=0.3, axis='y')

# Sales par segment client
segment_sales = df.groupby('Customer_Segment')['Sales'].mean().sort_values(ascending=False)
axes[1, 0].bar(segment_sales.index, segment_sales.values, color='purple', edgecolor='black', linewidth=2)
axes[1, 0].set_title('Revenu Moyen par Segment Client', fontsize=14, fontweight='bold')
axes[1, 0].set_xlabel('Segment Client')
axes[1, 0].set_ylabel('Revenu Moyen ($)')
axes[1, 0].tick_params(axis='x', rotation=45)
axes[1, 0].grid(alpha=0.3, axis='y')

# Units_Sold par segment
segment_units = df.groupby('Customer_Segment')['Units_Sold'].mean().sort_values(ascending=False)
axes[1, 1].bar(segment_units.index, segment_units.values, color='green', edgecolor='black', linewidth=2)
axes[1, 1].set_title('Unités Vendues Moyennes par Segment', fontsize=14, fontweight='bold')
axes[1, 1].set_xlabel('Segment Client')
axes[1, 1].set_ylabel('Unités Vendues Moyennes')
axes[1, 1].tick_params(axis='x', rotation=45)
axes[1, 1].grid(alpha=0.3, axis='y')

plt.tight_layout()
plt.show()

print("✅ Graphiques de ventes par catégorie et segment créés!")

"""## commentaire
Les catégories affichent des revenus moyens quasi-identiques (15000-16000$), avec Fashion et Sports légèrement devant. Les unités vendues sont aussi uniformes (~29 unités par catégorie), indiquant une performance équilibrée. Pour les segments clients, Premium génère 15500$ en revenu moyen avec 30 unités vendues, légèrement supérieur à Regular (14800$) et Occasional (14700$). Les différences sont minimes mais consistent. Conclusion : aucune catégorie ou segment ne surperforme drastiquement. Focus recommandé sur l'optimisation globale plutôt que favoriser une catégorie spécifique.

TENDANCES TEMPORELLES
"""

# Tendances temporelles - Ventes mensuelles
# Convertir la colonne 'Date' en datetime
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')

# Extraire l'année et le mois
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month

monthly_sales = df.groupby(['Year', 'Month'])['Sales'].sum().reset_index()
monthly_sales['Period'] = pd.to_datetime(monthly_sales[['Year', 'Month']].assign(DAY=1))

plt.figure(figsize=(16, 6))
plt.plot(monthly_sales['Period'], monthly_sales['Sales'], marker='o', linewidth=2.5,
         markersize=8, color='darkblue')
plt.fill_between(monthly_sales['Period'], monthly_sales['Sales'], alpha=0.3, color='lightblue')
plt.title('Évolution des Ventes Mensuelles', fontsize=16, fontweight='bold')
plt.xlabel('Période')
plt.ylabel('Ventes Totales ($)')
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

print("=" * 70)
print("VENTES TOTALES PAR MOIS")
print("=" * 70)
print(monthly_sales.to_string(index=False))

"""## commentaire
L’évolution mensuelle des ventes reste globalement stable entre 400 000 et 550 000 dollars, sans chute brutale ni tendance décroissante marquée. On observe toutefois plusieurs pics réguliers où les ventes dépassent 520 000 dollars, ce qui suggère des périodes plus fortes (probablement liées à des campagnes marketing ou à la saisonnalité). Globalement, l’activité e‑commerce est saine et relativement constante dans le temps, ce qui facilite la prévision et la planification des stocks.

# PRÉPARATION DES DONNÉES POUR LE MACHINE LEARNING :

ENCODAGE DES VARIABLES CATÉGORIELLES
"""

# Copie du dataframe pour le ML
df_ml = df.copy()

# Label Encoding pour les variables catégorielles
le_category = LabelEncoder()
le_segment = LabelEncoder()

df_ml['Product_Category_Encoded'] = le_category.fit_transform(df_ml['Product_Category'])
df_ml['Customer_Segment_Encoded'] = le_segment.fit_transform(df_ml['Customer_Segment'])

print("✅ Encodage terminé!")
print("\n" + "=" * 70)
print("MAPPING DES CATÉGORIES")
print("=" * 70)
print("\nProduct_Category:")
for i, cat in enumerate(le_category.classes_):
    print(f"  {cat} -> {i}")

print("\nCustomer_Segment:")
for i, seg in enumerate(le_segment.classes_):
    print(f"  {seg} -> {i}")

print("\n" + "=" * 70)
print("APERÇU DES DONNÉES ENCODÉES")
print("=" * 70)
print(df_ml[['Product_Category', 'Product_Category_Encoded', 'Customer_Segment', 'Customer_Segment_Encoded']].head(10))

"""SÉLECTION DES FEATURES"""

# Copie du dataframe pour le ML
df_ml = df.copy()

# Label Encoding pour les variables catégorielles
le_category = LabelEncoder()
le_segment = LabelEncoder()

df_ml['Product_Category_Encoded'] = le_category.fit_transform(df_ml['Product_Category'])
df_ml['Customer_Segment_Encoded'] = le_segment.fit_transform(df_ml['Customer_Segment'])

# Convertir la colonne 'Date' en datetime si ce n'est pas déjà fait pour df_ml
df_ml['Date'] = pd.to_datetime(df_ml['Date'], format='%d-%m-%Y', errors='coerce')

# Extraire les caractéristiques temporelles de la date
df_ml['Year'] = df_ml['Date'].dt.year
df_ml['Month'] = df_ml['Date'].dt.month
df_ml['Day'] = df_ml['Date'].dt.day
df_ml['DayOfWeek'] = df_ml['Date'].dt.dayofweek
df_ml['Quarter'] = df_ml['Date'].dt.quarter

print("✅ Encodage et ajout de caractéristiques temporelles terminés!")
print("\n" + "=" * 70)
print("MAPPING DES CATÉGORIES")
print("=" * 70)
print("\nProduct_Category:")
for i, cat in enumerate(le_category.classes_):
    print(f"  {cat} -> {i}")

print("\nCustomer_Segment:")
for i, seg in enumerate(le_segment.classes_):
    print(f"  {seg} -> {i}")

print("\n" + "=" * 70)
print("APERÇU DES DONNÉES ENCODÉES ET AVEC FEATURES TEMPORELLES")
print("=" * 70)
print(df_ml[['Product_Category', 'Product_Category_Encoded', 'Customer_Segment', 'Customer_Segment_Encoded', 'Date', 'Year', 'Month', 'Day', 'DayOfWeek', 'Quarter']].head(10))

# Features pour prédire Units_Sold
feature_columns = [
    'Price',
    'Discount',
    'Marketing_Spend',
    'Product_Category_Encoded',
    'Customer_Segment_Encoded',
    'Month',
    'DayOfWeek',
    'Quarter'
]

X = df_ml[feature_columns]
y = df_ml['Units_Sold']

print("\n" + "=" * 70)
print("FEATURES SÉLECTIONNÉES POUR LE MODÈLE")
print("=" * 70)
print(f"\nNombre de features: {X.shape[1]}")
print(f"Nombre d'observations: {X.shape[0]}")
print(f"\nListe des features:")
for i, col in enumerate(feature_columns, 1):
    print(f"  {i}. {col}")

print("\n" + "=" * 70)
print("VARIABLE CIBLE: Units_Sold")
print("=" * 70)
print(f"Moyenne: {y.mean():.2f}")
print(f"Médiane: {y.median():.2f}")
print(f"Min: {y.min()}")
print(f"Max: {y.max()}")

print("\n" + "=" * 70)
print("APERÇU DES FEATURES")
print("=" * 70)
print(X.head())

"""SPLIT TRAIN/TEST"""

# Division des données en train et test (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("=" * 70)
print("DIVISION DES DONNÉES")
print("=" * 70)
print(f"\nTaille du jeu d'entraînement: {X_train.shape[0]} lignes ({X_train.shape[0]/len(X)*100:.1f}%)")
print(f"Taille du jeu de test: {X_test.shape[0]} lignes ({X_test.shape[0]/len(X)*100:.1f}%)")

print("\n" + "=" * 70)
print("STATISTIQUES - JEU D'ENTRAÎNEMENT")
print("=" * 70)
print(f"y_train - Moyenne: {y_train.mean():.2f}")
print(f"y_train - Médiane: {y_train.median():.2f}")
print(f"y_train - Min: {y_train.min()}, Max: {y_train.max()}")

print("\n" + "=" * 70)
print("STATISTIQUES - JEU DE TEST")
print("=" * 70)
print(f"y_test - Moyenne: {y_test.mean():.2f}")
print(f"y_test - Médiane: {y_test.median():.2f}")
print(f"y_test - Min: {y_test.min()}, Max: {y_test.max()}")

"""STANDARDISATION (SCALING)"""

# Standardisation des features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("✅ Standardisation terminée!")
print("\n" + "=" * 70)
print("VÉRIFICATION DE LA STANDARDISATION")
print("=" * 70)

print("\nMoyennes après scaling (train set):")
print(X_train_scaled.mean(axis=0).round(2))

print("\nÉcart-types après scaling (train set):")
print(X_train_scaled.std(axis=0).round(2))

print("\n" + "=" * 70)
print("AVANT et APRÈS SCALING")
print("=" * 70)
print("\nAVANT (X_train original):")
print(X_train.describe().T[['mean', 'std']])

print("\nAPRÈS (X_train_scaled):")
df_scaled_stats = pd.DataFrame(X_train_scaled, columns=feature_columns)
print(df_scaled_stats.describe().T[['mean', 'std']])

# Convertir en DataFrame pour voir plus clairement
X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=feature_columns)
X_test_scaled_df = pd.DataFrame(X_test_scaled, columns=feature_columns)

print("\n✅ Les données sont maintenant normalisées (moyenne ≈ 0, écart-type ≈ 1)")

"""FONCTION D'ÉVALUATION"""

def evaluate_model(model, X_train, X_test, y_train, y_test, model_name):
    """
    Évalue un modèle et affiche les métriques de performance
    """
    # Prédictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Métriques Train
    train_mae = mean_absolute_error(y_train, y_train_pred)
    train_mse = mean_squared_error(y_train, y_train_pred)
    train_rmse = np.sqrt(train_mse)
    train_r2 = r2_score(y_train, y_train_pred)

    # Métriques Test
    test_mae = mean_absolute_error(y_test, y_test_pred)
    test_mse = mean_squared_error(y_test, y_test_pred)
    test_rmse = np.sqrt(test_mse)
    test_r2 = r2_score(y_test, y_test_pred)

    # Affichage
    print("=" * 70)
    print(f"📊 RÉSULTATS: {model_name}")
    print("=" * 70)
    print(f"\n{'Métrique':<20} {'Train':<15} {'Test':<15}")
    print("-" * 70)
    print(f"{'MAE':<20} {train_mae:<15.4f} {test_mae:<15.4f}")
    print(f"{'MSE':<20} {train_mse:<15.4f} {test_mse:<15.4f}")
    print(f"{'RMSE':<20} {train_rmse:<15.4f} {test_rmse:<15.4f}")
    print(f"{'R² Score':<20} {train_r2:<15.4f} {test_r2:<15.4f}")

    return {
        'model_name': model_name,
        'train_mae': train_mae,
        'test_mae': test_mae,
        'train_r2': train_r2,
        'test_r2': test_r2,
        'test_rmse': test_rmse,
        'y_test_pred': y_test_pred
    }

print("✅ Fonction d'évaluation créée!")

"""LINEAR REGRESSION"""

# Modèle 1: Linear Regression
lr_model = LinearRegression()
lr_model.fit(X_train_scaled, y_train)

lr_results = evaluate_model(lr_model, X_train_scaled, X_test_scaled, y_train, y_test, "Linear Regression")

print("\n" + "=" * 70)
print("COEFFICIENTS DU MODÈLE LINEAR REGRESSION")
print("=" * 70)
coefficients = pd.DataFrame({
    'Feature': feature_columns,
    'Coefficient': lr_model.coef_
}).sort_values('Coefficient', key=abs, ascending=False)
print(coefficients)

"""RIDGE REGRESSION"""

# Modèle 2: Ridge Regression
ridge_model = Ridge(alpha=1.0, random_state=42)
ridge_model.fit(X_train_scaled, y_train)

ridge_results = evaluate_model(ridge_model, X_train_scaled, X_test_scaled, y_train, y_test, "Ridge Regression")

print("\n" + "=" * 70)
print("COEFFICIENTS DU MODÈLE RIDGE REGRESSION")
print("=" * 70)
ridge_coefficients = pd.DataFrame({
    'Feature': feature_columns,
    'Coefficient': ridge_model.coef_
}).sort_values('Coefficient', key=abs, ascending=False)
print(ridge_coefficients)

# Modèle 4: Decision Tree
dt_model = DecisionTreeRegressor(max_depth=10, min_samples_split=10, random_state=42)
dt_model.fit(X_train, y_train)

dt_results = evaluate_model(dt_model, X_train, X_test, y_train, y_test, "Decision Tree")

# Modèle 5: Random Forest
rf_model = RandomForestRegressor(n_estimators=100, max_depth=15, random_state=42, n_jobs=-1)
rf_model.fit(X_train, y_train)

rf_results = evaluate_model(rf_model, X_train, X_test, y_train, y_test, "Random Forest")

# Modèle 6: Gradient Boosting
gb_model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=5, random_state=42)
gb_model.fit(X_train, y_train)

gb_results = evaluate_model(gb_model, X_train, X_test, y_train, y_test, "Gradient Boosting")

"""📊 COMPARAISON DES MODÈLES"""

# Modèle 3: Lasso Regression
lasso_model = Lasso(alpha=0.1, random_state=42)
lasso_model.fit(X_train_scaled, y_train)

lasso_results = evaluate_model(lasso_model, X_train_scaled, X_test_scaled, y_train, y_test, "Lasso Regression")

print("\n" + "=" * 70)
print("COEFFICIENTS DU MODÈLE LASSO REGRESSION")
print("=" * 70)
lasso_coefficients = pd.DataFrame({
    'Feature': feature_columns,
    'Coefficient': lasso_model.coef_
}).sort_values('Coefficient', key=abs, ascending=False)
print(lasso_coefficients)

# Créer un tableau comparatif de tous les modèles
all_results = [lr_results, ridge_results, lasso_results, dt_results, rf_results, gb_results]

results_df = pd.DataFrame([
    {
        'Modèle': result['model_name'],
        'Train R²': result['train_r2'],
        'Test R²': result['test_r2'],
        'Test RMSE': result['test_rmse'],
        'Test MAE': result['test_mae']
    }
    for result in all_results
])

print("=" * 90)
print("COMPARAISON DE TOUS LES MODÈLES")
print("=" * 90)
print(results_df.to_string(index=False))

# Meilleur modèle
best_idx = results_df['Test R²'].idxmax()
best_model_name = results_df.loc[best_idx, 'Modèle']
best_r2 = results_df.loc[best_idx, 'Test R²']

print("\n" + "=" * 90)
print(f"🏆 MEILLEUR MODÈLE: {best_model_name} (R² = {best_r2:.4f})")
print("=" * 90)

"""# VISUALISATION DES MODÈLES"""

# Graphique 1: Comparaison R² Score
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# R² Score
axes[0].bar(results_df['Modèle'], results_df['Test R²'], color='steelblue', edgecolor='black', linewidth=2)
axes[0].set_title('R² Score (Test Set)', fontsize=14, fontweight='bold')
axes[0].set_ylabel('R² Score')
axes[0].tick_params(axis='x', rotation=45)
axes[0].grid(alpha=0.3, axis='y')
axes[0].axhline(y=results_df['Test R²'].mean(), color='red', linestyle='--', label='Moyenne')
axes[0].legend()

# RMSE
axes[1].bar(results_df['Modèle'], results_df['Test RMSE'], color='coral', edgecolor='black', linewidth=2)
axes[1].set_title('RMSE (Test Set)', fontsize=14, fontweight='bold')
axes[1].set_ylabel('RMSE')
axes[1].tick_params(axis='x', rotation=45)
axes[1].grid(alpha=0.3, axis='y')

plt.tight_layout()
plt.show()

print("✅ Graphiques créés!")

"""# ANALYSE DES PRÉDICTIONS DU MEILLEUR MODÈLE"""

# Utiliser le meilleur modèle (Random Forest généralement)
best_model = rf_model
y_pred_test = best_model.predict(X_test)

# Graphique 1: Valeurs réelles vs prédites
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Scatter plot
axes[0].scatter(y_test, y_pred_test, alpha=0.6, color='blue', edgecolor='black')
axes[0].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2, label='Ligne parfaite')
axes[0].set_title('Valeurs Réelles vs Prédictions', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Valeurs Réelles (Units_Sold)')
axes[0].set_ylabel('Valeurs Prédites')
axes[0].grid(alpha=0.3)
axes[0].legend()

# Résidus
residuals = y_test - y_pred_test
axes[1].scatter(y_pred_test, residuals, alpha=0.6, color='purple', edgecolor='black')
axes[1].axhline(y=0, color='r', linestyle='--', lw=2)
axes[1].set_title('Analyse des Résidus', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Valeurs Prédites')
axes[1].set_ylabel('Résidus (Réel - Prédit)')
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

print("✅ Graphiques d'analyse créés!")

"""# IMPORTANCE DES FEATURES (Random Forest)"""

# Importance des features
feature_importance = pd.DataFrame({
    'Feature': feature_columns,
    'Importance': rf_model.feature_importances_
}).sort_values('Importance', ascending=False)

print("=" * 70)
print("IMPORTANCE DES FEATURES")
print("=" * 70)
print(feature_importance.to_string(index=False))

# Visualisation
plt.figure(figsize=(12, 8))
plt.barh(feature_importance['Feature'], feature_importance['Importance'],
         color='teal', edgecolor='black', linewidth=2)
plt.title('Importance des Features (Random Forest)', fontsize=16, fontweight='bold')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.gca().invert_yaxis()
plt.grid(alpha=0.3, axis='x')
plt.tight_layout()
plt.show()

print("\n✅ Graphique créé!")

print("=" * 80)
print("📊 RÉSUMÉ COMPLET DE L'ANALYSE E-COMMERCE")
print("=" * 80)

print(f"""
✅ DATASET ANALYSÉ
   • Nombre de transactions: {df.shape[0]}
   • Période: {df['Date'].min().strftime('%d/%m/%Y')} à {df['Date'].max().strftime('%d/%m/%Y')}
   • Nombre de features: {len(feature_columns)}

💰 STATISTIQUES FINANCIÈRES
   • Revenu total: ${df['Sales'].sum():,.2f}
   • Revenu moyen: ${df['Sales'].mean():,.2f}
   • Unités vendues: {df['Units_Sold'].sum()} unités

🏆 MEILLEUR MODÈLE
   • Modèle: {best_model_name}
   • R² Score (Train): {results_df.loc[best_idx, 'Train R²']:.4f}
   • R² Score (Test): {results_df.loc[best_idx, 'Test R²']:.4f}
   • RMSE (Test): {results_df.loc[best_idx, 'Test RMSE']:.4f}

📌 INSIGHTS CLÉS
   • Variable la plus importante: {feature_importance.iloc[0]['Feature']} ({feature_importance.iloc[0]['Importance']:.4f})
   • Corrélation Prix-Ventes: {df['Price'].corr(df['Units_Sold']):.4f}
   • Corrélation Marketing-Ventes: {df['Marketing_Spend'].corr(df['Units_Sold']):.4f}
   • Corrélation Réduction-Ventes: {df['Discount'].corr(df['Units_Sold']):.4f}

✨ CATÉGORIES LES PLUS RENTABLES
""")

top_categories = df.groupby('Product_Category')['Sales'].mean().sort_values(ascending=False)
for cat, sales in top_categories.items():
    print(f"   • {cat}: ${sales:,.2f}")

print(f"""
👥 SEGMENTS CLIENTS LES PLUS RENTABLES
""")

top_segments = df.groupby('Customer_Segment')['Sales'].mean().sort_values(ascending=False)
for seg, sales in top_segments.items():
    print(f"   • {seg}: ${sales:,.2f}")

print("\n" + "=" * 80)
print("🎉 ANALYSE COMPLÈTE TERMINÉE !")
print("=" * 80)

"""SAUVEGARDE DU MODÈLE"""

import pickle

# Sauvegarder le modèle
with open('rf_model.pkl', 'wb') as f:
    pickle.dump(rf_model, f)

print("✅ Modèle sauvegardé!")